name: learn-github-actions
on:
 push:
  paths-ignore:
    - '.github/**'
jobs:
  basic-env:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Find breakpoints
      run: grep -r "breakpoint()" *.py
      id: find_br
    - name: Check status error
      run: echo $?
      id: exit_status
    - name: End by breakpoints
      if: steps.exit_status.outcome == 0
      run: exit 1
      continue-on-error: false
